# Generated by Django 4.2.12 on 2025-11-18 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_post_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='pubilsh_date',
        ),
        migrations.RemoveField(
            model_name='post',
            name='status',
        ),
    ]
